<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->
 
<?php if ($this->pageCount): ?>
<div class="pagination">
<!-- <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?> 
of <?php echo $this->totalItemCount; ?> -->
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->restUrl(array('page' => $this->first)); ?>">
    Najnowsze
  </a> |
<?php else: ?>
  <span class="disabled">Najnowsze</span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->restUrl(array('page' => $this->previous)); ?>">
    &lt; Nowsze
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Nowsze</span> |
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->restUrl(array('page' => $page)); ?>">
        <?php echo $page; ?></a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->restUrl(array('page' => $this->next)); ?>">
    Starsze &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Starsze &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->restUrl(array('page' => $this->last)); ?>">
    Najstarsze
  </a>
<?php else: ?>
  <span class="disabled">Najstarsze</span>
<?php endif; ?>
 
</div>
<?php endif; ?>