version: "2"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - 8080:20222
        volumes:
            - ./app:/app
            - ./conf/nginx/site.conf:/etc/nginx/conf.d/site.conf
        environment:
            - APPLICATION_ENV=development
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - ./app:/app
            - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        environment:
            - APPLICATION_ENV=development