FROM phpdockerio/php7-fpm:latest

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y install software-properties-common memcached libmemcached-tools php-memcache php7.0-mysql php-memcached \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

ENV NODE_ENV development
ENV APPLICATION_ENV development

RUN mkdir /var/log/hhbd-website
RUN chown www-data:www-data /var/log/hhbd-website
