      <div id="nav">
        <ul>
          <!-- <li><a href="<?php echo $this->baseUrl(); ?>/top10.html">Top 10</a></li>  -->
          <li><a href="<?php echo $this->baseUrl(); ?>/albumy.html">Albumy</a></li>
          <li><a href="<?php echo $this->url(array(), 'announced'); ?>">Premiery</a></li>
          <li><a href="<?php echo $this->url(array(), 'artists'); ?>">Wykonawcy</a></li>
          <li><a href="<?php echo $this->url(array(), 'labels'); ?>">Wytwórnie</a></li>
          <!-- <li><a href="<?php echo $this->baseUrl(); ?>/teksty.html">Teksty</a></li>  -->
        </ul>

        <div id="search">
          <form action="<?php echo $this->url(array(), 'search') ?>">
            <label for="q" class="hidden">Szukaj:&nbsp;</label>
            <input type="text" name="q" value="" placeholder="Przeszukuj polski hip-hop..." autocomplete="off" id="q" title="Szukaj" tabindex="1" />
            <input type="submit" value="Szukaj &rarr;" />
          </form>
        </div>
      </div>
