<?xml version='1.0' encoding='UTF-8'?>
<sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd"
         xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <sitemap>
      <sitemap>
        <loc><?php echo $this->baseUrl() ?>/sitemap-albums.xml</loc>
        <lastmod><?php echo $this->hourAgo; ?></lastmod>
      </sitemap>
      <sitemap>
        <loc><?php echo $this->baseUrl() ?>/sitemap-artists.xml</loc>
        <lastmod><?php echo $this->hourAgo; ?></lastmod>
      </sitemap>
      <sitemap>
        <loc><?php echo $this->baseUrl() ?>/sitemap-news.xml</loc>
        <lastmod><?php echo $this->hourAgo; ?></lastmod>
      </sitemap>
      <sitemap>
        <loc><?php echo $this->baseUrl() ?>/sitemap-songs.xml</loc>
        <lastmod><?php echo $this->hourAgo; ?></lastmod>
      </sitemap>
      <sitemap>
        <loc><?php echo $this->baseUrl() ?>/sitemap-labels.xml</loc>
        <lastmod><?php echo $this->dayAgo; ?></lastmod>
      </sitemap>
   </sitemap>
</sitemapindex>
