<div id="main">
  
  <div class="pane">
    <h2>Kontakt</h2>
    <p>We wszystkich sprawach pisz do nas na adres <strong>kontakt@hhbd.pl</strong>.</p>
    <p>Miej jednak na uwdze, że nie wysyłamy żadnych albumów, poza konkursami, nie udostępniamy bezpośredniego kontaktu do wykonawców, oraz nie przekazujemy im bezpośrednio demówek!</p>
  </div>
  
</div>

<div id="additional">
  <div class="box">
    <h3>Ekipa</h3>
    <ul class="list">
      <li>Marcin Kazmiruk - redaktor naczelny</li>
      <li>Jakub Kułak - utrzymanie, rozwój</li>
    </ul>
  </div>
</div>