<div class="box googleads">
  <h3 class="hidden">Google Ads</h3>
  <?php echo $this->partial('common/googleAds/_rectangle.phtml'); ?>
</div>

<div class="box user hidden">
  <h3>Personalizacja</h3>
  <ul>
    <li>W kolekcji: <span class="button">Dodaj do kolekcji</span></li>
    <li>W chcęliście: <span class="button">Dodaj do chcęlisty</span></li>
  </ul>
</div>

<div class="box teksty lyrics hidden">
  <h3>Teksty piosenek</h3>
  Sprawdź dostępne na naszej stronie teksty piosenek, wystarczy, że wybierzesz któryś utwór z playlisty.
</div>

<?php echo $this->partial('album/box/_list.phtml', array('boxId' => 'artistsalbums', 'boxHeader' => 'Inne albumy ' . $this->album->artist->name, 'albums' => $this->artistsAlbums, 'showCovers' => true)) ?>

<?php if (!empty($this->album->label) AND (!empty($this->album->label->name))): ?>
  <?php echo $this->partial('album/box/_list.phtml', array('boxId' => 'labelsalbums', 'boxHeader' => 'Inne albumy wydane przez ' . $this->album->label->name, 'albums' => $this->labelsAlbums, 'showCovers' => false)) ?>
<?php endif ?>

<?php echo $this->render('album/box/_bestRated.phtml') ?>

<?php echo $this->partial('album/box/_list.phtml', array('boxId' => 'artistsalbums', 'boxHeader' => 'Najpopularniejsze albumy', 'albums' => $this->popularAlbums)) ?>

<div class="box wrzuta chomikuj hidden">
  <h3>Linki</h3>
  <ul>
    <li>Wrzuta.pl</li>
    <li>Chomikuj.pl</li>
  </ul>
</div>
