<div class="pagination">
  <span class="pages">
    <?php if ($this->current == 'mostPopular'): ?>
      <span class="active">Najpopularniejsi</span>
    <?php else: ?>
      <a href="<?php echo $this->url(array(), 'artists'); ?>">Najpopularniejsi</a>
    <?php endif ?>
  <?php foreach ($this->firstLetters as $letter): ?> 
    <?php if ($letter['name'] != $this->current): ?>
      <a href="<?php echo $this->restUrl(array('letter' => $letter['name'])); ?>"><?php echo $letter['name']; ?></a>
    <?php else: ?>
      <span class="active"><?php echo $letter['name']; ?></span>
    <?php endif; ?>
<?php endforeach; ?>
  </span>
</div>