<div class="box googleads">
  <h3 class="hidden">Google Ads</h3>
  <?php echo $this->partial('common/googleAds/_rectangle.phtml'); ?>
</div>

<?php foreach ($this->albumSongs as $key => $value): ?>
  <?php echo $this->partial('song/box/_list.phtml', array('boxId' => 'albumSongs', 'boxHeader' => 'Utwory z albumu "' . $this->song->featured->items[$key]->title . '"', 'songs' => $value)) ?>  
<?php endforeach ?>


<?php echo $this->partial('song/box/_list.phtml', array('boxId' => 'songs', 'boxHeader' => 'Najpopularniejsze utwory na www.hhbd.pl', 'songs' => $this->popularSongs)) ?>